spring:
  security:
    jwt:
      secret: sdfjksdjfksjs
      expire: 3
  datasource:
    url: jdbc:mysql://localhost:3306/jwtstudy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: gnengjun@163.com
    password: NNTYARNEDWSJKIKM
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    virtual-host: /